version: '2.1'

services:
  application-server:
    build: ./application
    restart: always
    depends_on:
      - database-server
    ports:
     - 80:8888
  
  database-server:
    build: ./database
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
  
volumes:
  mysql-db:
